all: lake_key.png buffer_key.png proxy_key.png transport_key.png input_key.png

lake_key.png:
	colorconvert red noun_Water_37865.png lake_key.png

buffer_key.png:
	colorconvert orange noun_Checkerboard_852829.png buffer_key.png

proxy_key.png:
	colorconvert green noun_GrainsSilo_649410.png proxy_key.png

transport_key.png:
	colorconvert purple noun_river_1629939.png transport_key.png

input_key.png:
	colorconvert blue noun_Outfall_25100.png input_key.png

